version: '3.8'

services:
  osrm:
    image: osrm/osrm-backend:latest
    container_name: osrm-backend
    ports:
      - "5005:5000"
    volumes:
      - ./backend/osrm_data:/data
    command: osrm-routed --algorithm ch /data/philippines-latest.osrm
    restart: unless-stopped
